In [1]:
using Optim
using Plots

In [2]:
default(size = (300, 200)) # plot size

# Generate data

In [3]:
f1(x) = x^2/20 + sin(2*x)

f1 (generic function with 1 method)

In [4]:
x = reshape([-10:0.1:10;],1,:) # shape = [n_input,n_sample]
y_true = f1.(x)
print(size(x), size(y_true))
plot(x[:], y_true[:])

(1, 201)(1, 201)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -10 
 
 
 -5 
 
 
 0 
 
 
 5 
 
 
 10 
 
 
 0 
 
 
 2 
 
 
 4 
 
<polyline clip-path="url(#clip02)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 22.3377,55.3325 23.6275,55.338 24.9174,54.5464 26.2073,53.0829 27.4972,51.0986 28.7871,48.7641 30.077,46.2635 31.3669,43.786 32.6568,41.5194 33.9466,39.642 
 35.2365,38.3154 36.5264,37.6786 37.8163,37.8421 39.1062,38.8833 40.3961,40.8441 41.686,43.7283 42.9758,47.5022 44.2657,52.0957 45.5556,57.405 46.8455,63.2968 
 48.1354,69.6138 49.4253,76.1804 50.7152,82.8106 52.0051,89.3145 53.2949,95.5066 54.5848,101.213 55.8747,106.277 57.1646,110.568 58.4545,113.985 59.7444,116.461 
 61.0343,117.965 62.3241,118.503 63.614,118.121 64.9039,116.899 66.1938,114.949 67.4837,112.413 68.7736,109.453 70.0635,106.25 71.3533,102.991 72.6432,99.8655 
 73.9331,97.0566 75.223,94.7337 76.5129,93.0461 77.8028,92.1165 79.0927,92.0367 80.3826,92.8635 81.6724,94.6167 82.9623,97.2782 84.2522,100.793 85.5421,105.07 
 86.832,109.989 88.1219,115.4 89.4118,121.137 90.7016,127.015 91.9915,132.845 93.2814,138.44 94.5713,143.62 95.8612,148.219 97.1511,152.097 98.441,155.14 
 99.7309,157.264 101.021,158.425 102.311,158.612 103.601,157.856 104.89,156.223 106.18,153.811 107.47,150.751 108.76,147.198 110.05,143.325 111.34,139.317 
 112.63,135.364 113.92,131.654 115.209,128.36 116.499,125.643 117.789,123.636 119.079,122.445 120.369,122.142 121.659,122.761 122.949,124.3 124.239,126.72 
 125.529,129.944 126.818,133.864 128.108,138.341 129.398,143.215 130.688,148.308 131.978,153.433 133.268,158.399 134.558,163.024 135.848,167.135 137.138,170.58 
 138.427,173.233 139.717,174.998 141.007,175.813 142.297,175.656 143.587,174.537 144.877,172.51 146.167,169.659 147.457,166.102 148.747,161.985 150.036,157.474 
 151.326,152.751 152.616,148.003 153.906,143.421 155.196,139.185 156.486,135.461 157.776,132.396 159.066,130.106 160.356,128.678 161.645,128.162 162.935,128.573 
 164.225,129.885 165.515,132.037 166.805,134.934 168.095,138.449 169.385,142.43 170.675,146.705 171.964,151.091 173.254,155.397 174.544,159.437 175.834,163.032 
 177.124,166.022 178.414,168.269 179.704,169.665 180.994,170.131 182.284,169.63 183.573,168.159 184.863,165.752 186.153,162.482 187.443,158.454 188.733,153.802 
 190.023,148.685 191.313,143.278 192.603,137.769 193.893,132.346 195.182,127.196 196.472,122.491 197.762,118.387 199.052,115.014 200.342,112.47 201.632,110.822 
 202.922,110.1 204.212,110.294 205.502,111.357 206.791,113.21 208.081,115.736 209.371,118.794 210.661,122.22 211.951,125.833 213.241,129.447 214.531,132.871 
 215.821,135.923 217.111,138.434 218.4,140.257 219.69,141.268 220.98,141.379 222.27,140.535 223.56,138.716 224.85,135.942 226.14,132.272 227.43,127.795 
 228.72,122.636 230.009,116.943 231.299,110.886 232.589,104.647 233.879,98.4167 235.169,92.3825 236.459,86.7238 237.749,81.6038 239.039,77.1635 240.328,73.5158 
 241.618,70.7411 242.908,68.8838 244.198,67.9511 245.488,67.9122 246.778,68.6997 248.068,70.2124 249.358,72.3192 250.648,74.8644 251.937,77.6738 253.227,80.5618 
 254.517,83.3385 255.807,85.8179 257.097,87.8245 258.387,89.2009 259.677,89.8139 260.967,89.5595 262.257,88.3678 263.546,86.2049 264.836,83.0749 266.126,79.0195 
 267.416,74.1161 268.706,68.4753 269.996,62.2358 271.286,55.5596 272.576,48.6249 273.866,41.6193 275.155,34.7322 276.445,28.1476 277.735,22.0361 279.025,16.5489 
 280.315,11.811 
 "/>
 
 
 
 
 y1

# Build NN

In [5]:
function init_weights(;n_in=1, n_hidden=10, n_out=1)
    W1 = randn(n_hidden, n_in) # for left multiply W1*x
    b1 = zeros(n_hidden)
    W2 = randn(n_out, n_hidden)
    b2 = zeros(n_out)
    params = [W1, b1, W2, b2]
    return params
end

params = init_weights()

4-element Array{Array{Float64,N} where N,1}:
 [0.177902; -1.77137; … ; 1.36901; -0.175861]      
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [1.22351 -0.932874 … -0.920088 -0.529654]         
 [0.0]                                             

In [6]:
params_flat = collect(Iterators.flatten(params))
sizes = map(size, params)

4-element Array{Tuple{Int64,Vararg{Int64,N} where N},1}:
 (10, 1)
 (10,)  
 (1, 10)
 (1,)   

In [7]:
const sizes_const = sizes

4-element Array{Tuple{Int64,Vararg{Int64,N} where N},1}:
 (10, 1)
 (10,)  
 (1, 10)
 (1,)   

In [8]:
function predict(params_flat, x; act=tanh)
    # unflatten
    params = []
    i1 = 1
    for s in sizes # sizes is global constant
        l = reduce(*, s) # size -> length
        i2 = i1+l
        p = reshape(params_flat[i1:i2-1], s)
        push!(params, p)
        i1 = i2
    end 
    
    W1, b1, W2, b2 = params
    
    # normal NN calculation
    
    a = act.(W1*x .+ b1)
    y = W2*a .+ b2
    return y
end

predict (generic function with 1 method)

In [9]:
y_pred = predict(params_flat, x)

1×201 Array{Float64,2}:
 -3.33572  -3.3355  -3.33519  -3.33479  …  3.33479  3.33519  3.3355  3.33572

In [10]:
plot(x[:], y_pred[:])

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -10 
 
 
 -5 
 
 
 0 
 
 
 5 
 
 
 10 
 
 
 -2 
 
 
 0 
 
 
 2 
 
<polyline clip-path="url(#clip02)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 29.2591,175.813 30.5144,175.808 31.7697,175.801 33.025,175.791 34.2803,175.778 35.5355,175.764 36.7908,175.746 38.0461,175.726 39.3014,175.703 40.5567,175.676 
 41.8119,175.647 43.0672,175.614 44.3225,175.578 45.5778,175.537 46.833,175.493 48.0883,175.445 49.3436,175.393 50.5989,175.336 51.8542,175.274 53.1094,175.208 
 54.3647,175.137 55.62,175.06 56.8753,174.978 58.1306,174.89 59.3858,174.796 60.6411,174.696 61.8964,174.589 63.1517,174.476 64.407,174.356 65.6622,174.228 
 66.9175,174.093 68.1728,173.95 69.4281,173.798 70.6834,173.638 71.9386,173.47 73.1939,173.292 74.4492,173.104 75.7045,172.907 76.9597,172.7 78.215,172.482 
 79.4703,172.253 80.7256,172.012 81.9809,171.76 83.2361,171.496 84.4914,171.219 85.7467,170.929 87.002,170.625 88.2573,170.308 89.5125,169.977 90.7678,169.63 
 92.0231,169.269 93.2784,168.891 94.5337,168.498 95.7889,168.087 97.0442,167.659 98.2995,167.214 99.5548,166.75 100.81,166.267 102.065,165.765 103.321,165.242 
 104.576,164.699 105.831,164.134 107.086,163.547 108.342,162.937 109.597,162.304 110.852,161.646 112.108,160.962 113.363,160.252 114.618,159.514 115.873,158.748 
 117.129,157.951 118.384,157.123 119.639,156.262 120.895,155.366 122.15,154.432 123.405,153.459 124.66,152.444 125.916,151.383 127.171,150.274 128.426,149.113 
 129.681,147.896 130.937,146.617 132.192,145.273 133.447,143.856 134.703,142.361 135.958,140.781 137.213,139.108 138.468,137.332 139.724,135.443 140.979,133.428 
 142.234,131.268 143.49,128.941 144.745,126.415 146,123.647 147.255,120.585 148.511,117.164 149.766,113.324 151.021,109.024 152.276,104.272 153.532,99.1481 
 154.787,93.8122 156.042,88.4764 157.298,83.3524 158.553,78.6001 159.808,74.3002 161.063,70.4603 162.319,67.0399 163.574,63.9773 164.829,61.2098 166.085,58.6836 
 167.34,56.3564 168.595,54.1967 169.85,52.1811 171.106,50.2922 172.361,48.5165 173.616,46.8432 174.872,45.2631 176.127,43.7683 177.382,42.3517 178.637,41.0071 
 179.893,39.7286 181.148,38.5111 182.403,37.3501 183.658,36.2412 184.914,35.1808 186.169,34.1655 187.424,33.1924 188.68,32.2588 189.935,31.3624 191.19,30.5011 
 192.445,29.673 193.701,28.8765 194.956,28.1101 196.211,27.3725 197.467,26.6624 198.722,25.9788 199.977,25.3207 201.232,24.6872 202.488,24.0773 203.743,23.4904 
 204.998,22.9256 206.253,22.3823 207.509,21.8597 208.764,21.3573 210.019,20.8745 211.275,20.4106 212.53,19.965 213.785,19.5373 215.04,19.1269 216.296,18.7332 
 217.551,18.3558 218.806,17.9942 220.062,17.6478 221.317,17.3162 222.572,16.999 223.827,16.6957 225.083,16.4057 226.338,16.1288 227.593,15.8645 228.849,15.6123 
 230.104,15.3719 231.359,15.1429 232.614,14.9248 233.87,14.7173 235.125,14.52 236.38,14.3326 237.635,14.1547 238.891,13.986 240.146,13.8262 241.401,13.6748 
 242.657,13.5316 243.912,13.3964 245.167,13.2687 246.422,13.1483 247.678,13.035 248.933,12.9284 250.188,12.8283 251.444,12.7344 252.699,12.6465 253.954,12.5644 
 255.209,12.4877 256.465,12.4163 257.72,12.35 258.975,12.2885 260.23,12.2317 261.486,12.1793 262.741,12.1312 263.996,12.0871 265.252,12.0469 266.507,12.0105 
 267.762,11.9776 269.017,11.948 270.273,11.9217 271.528,11.8985 272.783,11.8783 274.039,11.8608 275.294,11.846 276.549,11.8338 277.804,11.8239 279.06,11.8164 
 280.315,11.811 
 "/>
 
 
 
 
 y1

In [11]:
function loss_func(params_flat, x, y_true)
    y_pred = predict(params_flat, x)
    loss = mean(abs2 ,y_pred - y_true)
    return loss
end

loss_func (generic function with 1 method)

In [12]:
loss_func(params_flat, x, y_true)

13.685127558542781

# Optim.jl

In [13]:
# use global x and y for now
loss_wrap(params_flat) = loss_func(params_flat, x, y_true)

loss_wrap (generic function with 1 method)

In [14]:
params = init_weights(n_hidden = 10) # re-initialize weight
params_flat = collect(Iterators.flatten(params));

In [15]:
option = Optim.Options(iterations = 2000)

Optim.Options{Void}(1.0e-32, 1.0e-32, 1.0e-8, 0, 0, 0, false, 2000, false, false, false, 1, nothing, NaN)

In [16]:
@time opt = optimize(loss_wrap, params_flat, BFGS(), option)

 30.022794 seconds (30.32 M allocations: 12.413 GiB, 6.05% gc time)


Results of Optimization Algorithm
 * Algorithm: BFGS
 * Starting Point: [-0.0014598533367757788,-1.7767793156770935, ...]
 * Minimizer: [0.8413179480694707,-0.3771537230331488, ...]
 * Minimum: 5.249643e-04
 * Iterations: 2000
 * Convergence: false
   * |x - x'| < 1.0e-32: false 
     |x - x'| = 8.83e-02 
   * |f(x) - f(x')| / |f(x)| < 1.0e-32: false
     |f(x) - f(x')| / |f(x)| = NaN 
   * |g(x)| < 1.0e-08: false 
     |g(x)| = 3.91e-02 
   * stopped by an increasing objective: false
   * Reached Maximum Number of Iterations: true
 * Objective Calls: 5042
 * Gradient Calls: 5042

In [17]:
loss_wrap(opt.minimizer)

0.0005249642960746887

In [18]:
y_pred = predict(opt.minimizer, x)

1×201 Array{Float64,2}:
 3.92036  4.02945  4.13717  4.24251  …  5.21609  5.46376  5.70045  5.936

In [19]:
plot(x[:], y_true[:],lw=2)
plot!(x[:], y_pred[:],lw=0,
    marker=:circle,markerstrokewidth = 0,markersize=3)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -10 
 
 
 0 
 
 
 10 
 
 
 0.0 
 
 
 2.5 
 
 
 5.0 
 
<polyline clip-path="url(#clip02)" style="stroke:#009af9; stroke-width:2; stroke-opacity:1; fill:none" points="
 39.2436,57.8166 40.4139,57.8217 41.5841,57.0787 42.7543,55.7051 43.9246,53.8427 45.0948,51.6517 46.2651,49.3046 47.4353,46.9793 48.6056,44.8519 49.7758,43.0898 
 50.9461,41.8447 52.1163,41.247 53.2866,41.4005 54.4568,42.3778 55.6271,44.2181 56.7973,46.9251 57.9676,50.4672 59.1378,54.7786 60.3081,59.7617 61.4783,65.2917 
 62.6486,71.2206 63.8188,77.3839 64.9891,83.6068 66.1593,89.7113 67.3296,95.523 68.4998,100.879 69.6701,105.632 70.8403,109.659 72.0106,112.867 73.1808,115.191 
 74.3511,116.602 75.5213,117.107 76.6916,116.748 77.8618,115.601 79.0321,113.771 80.2023,111.391 81.3726,108.613 82.5428,105.606 83.7131,102.548 84.8833,99.6141 
 86.0536,96.9778 87.2238,94.7976 88.3941,93.2136 89.5643,92.3411 90.7346,92.2662 91.9048,93.0422 93.0751,94.6877 94.2453,97.1858 95.4156,100.484 96.5858,104.499 
 97.7561,109.116 98.9263,114.195 100.097,119.579 101.267,125.096 102.437,130.568 103.607,135.819 104.778,140.681 105.948,144.998 107.118,148.638 108.288,151.493 
 109.459,153.487 110.629,154.576 111.799,154.752 112.969,154.043 114.14,152.51 115.31,150.246 116.48,147.374 117.65,144.039 118.821,140.404 119.991,136.642 
 121.161,132.933 122.331,129.45 123.502,126.359 124.672,123.808 125.842,121.925 127.012,120.807 128.183,120.522 129.353,121.103 130.523,122.548 131.693,124.819 
 132.864,127.846 134.034,131.524 135.204,135.727 136.374,140.301 137.545,145.081 138.715,149.891 139.885,154.553 141.055,158.893 142.226,162.751 143.396,165.985 
 144.566,168.475 145.736,170.131 146.907,170.897 148.077,170.749 149.247,169.699 150.417,167.796 151.588,165.12 152.758,161.782 153.928,157.918 155.098,153.684 
 156.269,149.251 157.439,144.795 158.609,140.494 159.779,136.518 160.95,133.023 162.12,130.146 163.29,127.997 164.46,126.657 165.631,126.173 166.801,126.558 
 167.971,127.79 169.141,129.81 170.312,132.529 171.482,135.828 172.652,139.564 173.822,143.577 174.993,147.693 176.163,151.735 177.333,155.527 178.503,158.901 
 179.674,161.707 180.844,163.816 182.014,165.126 183.184,165.564 184.355,165.094 185.525,163.712 186.695,161.454 187.865,158.384 189.036,154.604 190.206,150.237 
 191.376,145.435 192.546,140.36 193.717,135.189 194.887,130.1 196.057,125.266 197.227,120.85 198.398,116.998 199.568,113.832 200.738,111.444 201.908,109.898 
 203.079,109.22 204.249,109.402 205.419,110.4 206.589,112.139 207.76,114.509 208.93,117.38 210.1,120.595 211.27,123.987 212.441,127.379 213.611,130.592 
 214.781,133.457 215.951,135.814 217.121,137.524 218.292,138.474 219.462,138.578 220.632,137.785 221.802,136.078 222.973,133.475 224.143,130.03 225.313,125.828 
 226.483,120.986 227.654,115.643 228.824,109.957 229.994,104.102 231.164,98.2544 232.335,92.5908 233.505,87.2796 234.675,82.4742 235.845,78.3066 237.016,74.883 
 238.186,72.2787 239.356,70.5355 240.526,69.6601 241.697,69.6235 242.867,70.3627 244.037,71.7825 245.207,73.7599 246.378,76.1487 247.548,78.7856 248.718,81.4961 
 249.888,84.1024 251.059,86.4294 252.229,88.3128 253.399,89.6046 254.569,90.1799 255.74,89.9412 256.91,88.8227 258.08,86.7927 259.25,83.8549 260.421,80.0486 
 261.591,75.4464 262.761,70.152 263.931,64.2959 265.102,58.0297 266.272,51.521 267.442,44.9456 268.612,38.4816 269.783,32.3014 270.953,26.5654 272.123,21.4152 
 273.293,16.9683 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#e26f46; stroke-width:0; stroke-opacity:1; fill:none" points="
 39.2436,61.5458 40.4139,59.1053 41.5841,56.6953 42.7543,54.3388 43.9246,52.064 45.0948,49.9048 46.2651,47.9018 47.4353,46.103 48.6056,44.5641 49.7758,43.3492 
 50.9461,42.5299 52.1163,42.1844 53.2866,42.3949 54.4568,43.2437 55.6271,44.8071 56.7973,47.1481 57.9676,50.3064 59.1378,54.2887 60.3081,59.0584 61.4783,64.5288 
 62.6486,70.5604 63.8188,76.965 64.9891,83.5168 66.1593,89.9701 67.