In [1]:
using Optim
using AutoGrad
using Plots
using DifferentialEquations

In [2]:
default(size = (300, 200)) # plot size

# Generate data

In [3]:
#f1(t, y) = t^2/20 + sin(2*t)
f1(t, y) = -y + sin(t)

f1 (generic function with 1 method)

In [4]:
t = reshape([0.0:0.1:6.0;],1,:) # shape = [n_input,n_sample]

1×61 Array{Float64,2}:
 0.0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  …  5.4  5.5  5.6  5.7  5.8  5.9  6.0

# Solve by DifferentialEquations.jl

In [5]:
prob = ODEProblem(f1, 1.0, (0.0, 6.0))

DiffEqBase.ODEProblem with uType Float64 and tType Float64. In-place: false
timespan: (0.0, 6.0)
u0: 1.0

In [6]:
sol = solve(prob, saveat=0.1);
y_true = sol.u
size(y_true)

(61,)

In [7]:
plot(t[:], y_true, label="y")
plot!(t[:], f1.(t[:] ,y_true), label="dy/dt")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 3 
 
 
 4 
 
 
 5 
 
 
 6 
 
 
 -1.0 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
<polyline clip-path="url(#clip02)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 39.1436,11.811 43.1631,19.2181 47.1826,25.1446 51.2022,29.7431 55.2217,33.1594 59.2412,35.5326 63.2607,36.996 67.2802,37.6771 71.2998,37.6974 75.3193,37.1729 
 79.3388,36.2143 83.3583,34.9263 87.3779,33.4076 91.3974,31.7514 95.4169,30.0451 99.4364,28.3693 103.456,26.7984 107.475,25.4003 111.495,24.2363 115.515,23.361 
 119.534,22.8216 123.554,22.6587 127.573,22.9054 131.593,23.5881 135.612,24.7257 139.632,26.3299 143.651,28.4063 147.671,30.9536 151.69,33.9643 155.71,37.4241 
 159.729,41.3123 163.749,45.6017 167.768,50.2612 171.788,55.255 175.807,60.5432 179.827,66.0825 183.846,71.8257 187.866,77.7223 191.885,83.7181 195.905,89.7588 
 199.925,95.7897 203.944,101.755 207.964,107.601 211.983,113.273 216.003,118.718 220.022,123.883 224.042,128.721 228.061,133.185 232.081,137.233 236.1,140.826 
 240.12,143.931 244.139,146.519 248.159,148.566 252.178,150.052 256.198,150.965 260.217,151.296 264.237,151.042 268.256,150.206 272.276,148.797 276.295,146.832 
 280.315,144.33 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#e26f46; stroke-width:1; stroke-opacity:1; fill:none" points="
 39.1436,175.813 43.1631,160.22 47.1826,146.189 51.2022,133.648 55.2217,122.532 59.2412,112.778 63.2607,104.327 67.2802,97.1208 71.2998,91.103 75.3193,86.2178 
 79.3388,82.4085 83.3583,79.6181 87.3779,77.7885 91.3974,76.8601 95.4169,76.7713 99.4364,77.4594 103.456,78.8598 107.475,80.9065 111.495,83.5314 115.515,86.6657 
 119.534,90.2394 123.554,94.1816 127.573,98.4214 131.593,102.888 135.612,107.51 139.632,112.219 143.651,116.946 147.671,121.625 151.69,126.191 155.71,130.582 
 159.729,134.74 163.749,138.613 167.768,142.15 171.788,145.305 175.807,148.036 179.827,150.307 183.846,152.086 187.866,153.349 191.885,154.079 195.905,154.263 
 199.925,153.894 203.944,152.969 207.964,151.494 211.983,149.478 216.003,146.939 220.022,143.9 224.042,140.388 228.061,136.435 232.081,132.079 236.1,127.361 
 240.12,122.327 244.139,117.024 248.159,111.503 252.178,105.82 256.198,100.027 260.217,94.184 264.237,88.3476 268.256,82.5757 272.276,76.9252 276.295,71.4512 
 280.315,66.2066 
 "/>
 
 
 
 
 y 
 
 
 
 dy/dt

# Build NN

In [8]:
function init_weights(;n_in=1, n_hidden=10, n_out=1)
    W1 = randn(n_hidden, n_in) # for left multiply W1*x
    b1 = zeros(n_hidden)
    W2 = randn(n_out, n_hidden)
    b2 = zeros(n_out)
    params = [W1, b1, W2, b2]
    return params
end

params = init_weights()

4-element Array{Array{Float64,N} where N,1}:
 [-0.00300493; 0.0207061; … ; 0.109023; 1.14094]   
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.211986 0.551876 … 0.303775 -0.433967]          
 [0.0]                                             

In [9]:
params_flat = collect(Iterators.flatten(params))
sizes = map(size, params)

4-element Array{Tuple{Int64,Vararg{Int64,N} where N},1}:
 (10, 1)
 (10,)  
 (1, 10)
 (1,)   

In [10]:
function predict(params_flat, t; act=tanh, y0=1.0, t0=0.0)
    # unflatten
    params = []
    i1 = 1
    for s in sizes # sizes is defined outside of the function
        l = reduce(*, s) # size -> length
        i2 = i1+l
        p = reshape(params_flat[i1:i2-1], s)
        push!(params, p)
        i1 = i2
    end 
    
    W1, b1, W2, b2 = params
    
    # normal NN calculation
    a = act.(W1*t .+ b1)
    y = W2*a .+ b2
    
    # force intial condition
    phi = y0 .+ (t .- t0) .* y
    
    return phi
end

predict (generic function with 1 method)

In [11]:
f_pred = predict(params_flat, t)

1×61 Array{Float64,2}:
 1.0  0.9711  0.888161  0.76129  0.604077  …  -2.41305  -2.44334  -2.4735

In [12]:
plot(t[:], f_pred[:])

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 3 
 
 
 4 
 
 
 5 
 
 
 6 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
<polyline clip-path="url(#clip02)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 29.2591,11.811 33.4434,13.1755 37.6277,17.0915 41.8119,23.0818 45.9962,30.5046 50.1805,38.7039 54.3647,47.1183 58.549,55.3313 62.7333,63.0737 66.9175,70.1995 
 71.1018,76.6529 75.286,82.4388 79.4703,87.5976 83.6546,92.1888 87.8388,96.2792 92.0231,99.9355 96.2074,103.221 100.392,106.192 104.576,108.899 108.76,111.385 
 112.944,113.688 117.129,115.839 121.313,117.863 125.497,119.784 129.681,121.62 133.866,123.385 138.05,125.093 142.234,126.754 146.419,128.377 150.603,129.968 
 154.787,131.535 158.971,133.082 163.156,134.613 167.34,136.131 171.524,137.639 175.708,139.139 179.893,140.634 184.077,142.124 188.261,143.611 192.445,145.096 
 196.63,146.579 200.814,148.06 204.998,149.54 209.182,151.02 213.367,152.498 217.551,153.975 221.735,155.451 225.92,156.926 230.104,158.399 234.288,159.87 
 238.472,161.339 242.657,162.805 246.841,164.268 251.025,165.728 255.209,167.183 259.394,168.635 263.578,170.081 267.762,171.523 271.946,172.959 276.131,174.389 
 280.315,175.813 
 "/>
 
 
 
 
 y1

## Grad NN w.r.t to t

Autograd.jl only works with scalar. We can take the diagonal of the jacobian to "vectorize" over t.

In [13]:
predict_sum(params_flat, t) = sum(predict(params_flat, t))

predict_sum (generic function with 1 method)

In [14]:
predict_dt = grad(predict_sum, 2)

(::gradfun) (generic function with 1 method)

In [15]:
dfdt_pred = predict_dt(params_flat, t)

1×61 Array{Float64,2}:
 0.0  -0.571513  -1.06991  -1.4443  …  -0.30356  -0.302281  -0.300927

In [16]:
plot(t[:], dfdt_pred[:])

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 3 
 
 
 4 
 
 
 5 
 
 
 6 
 
 
 -1.5 
 
 
 -1.0 
 
 
 -0.5 
 
 
 0.0 
 
<polyline clip-path="url(#clip02)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 39.1436,11.811 43.1631,64.5639 47.1826,110.568 51.2022,145.125 55.2217,166.55 59.2412,175.813 63.2607,175.447 67.2802,168.428 71.2998,157.451 75.3193,144.61 
 79.3388,131.36 83.3583,118.62 87.3779,106.904 91.3974,96.4508 95.4169,87.32 99.4364,79.4669 103.456,72.7894 107.475,67.1598 111.495,62.4441 115.515,58.5132 
 119.534,55.249 123.554,52.5465 127.573,50.3147 131.593,48.4758 135.612,46.9639 139.632,45.7238 143.651,44.7093 147.671,43.882 151.69,43.2099 155.71,42.6663 
 159.729,42.2289 163.749,41.8794 167.768,41.6022 171.788,41.3842 175.807,41.2146 179.827,41.0841 183.846,40.985 187.866,40.9105 191.885,40.8551 195.905,40.814 
 199.925,40.7832 203.944,40.7593 207.964,40.7393 211.983,40.7209 216.003,40.7019 220.022,40.6807 224.042,40.6558 228.061,40.6261 232.081,40.5907 236.1,40.5488 
 240.12,40.5 244.139,40.4437 248.159,40.3797 252.178,40.3078 256.198,40.228 260.217,40.1403 264.237,40.0448 268.256,39.9415 272.276,39.8308 276.295,39.7127 
 280.315,39.5877 
 "/>
 
 
 
 
 y1

## Build loss function

In [17]:
function loss_func(params_flat, t)
    y_pred = predict(params_flat, t)
    dydt_pred = predict_dt(params_flat, t)
    f_pred = f1.(t, y_pred)
    loss = mean(abs2, dydt_pred - f_pred)
    return loss
end

loss_func (generic function with 1 method)

In [18]:
loss_func(params_flat, t)

3.9606397323790983

# Optim.jl

Objective function should only take one variable.

In [19]:
# use global t for now
loss_wrap(params_flat) = loss_func(params_flat, t)

loss_wrap (generic function with 1 method)

In [20]:
loss_wrap(params_flat)

3.9606397323790983

## Built-in Forward autodiff

- http://julianlsolvers.github.io/Optim.jl/stable/algo/autodiff/

Seems to speed up the optimizer by 200%

In [21]:
od = OnceDifferentiable(loss_wrap, params_flat; autodiff =:forward);
typeof(od)

NLSolversBase.OnceDifferentiable{Float64,Array{Float64,1}}

Do several steps of Momentum Gradient Descent to approach minimum, and then use BFGS to converge to minimum.

In [22]:
option1 = Optim.Options(iterations = 50, show_trace=true, show_every=50)
option2 = Optim.Options(iterations = 100, show_trace=true, show_every=50)

Optim.Options{Void}(1.0e-32, 1.0e-32, 1.0e-8, 0, 0, 0, false, 100, false, true, false, 50, nothing, NaN)

In [23]:
params = init_weights(n_hidden = 10) # re-initialize weight
params_flat = collect(Iterators.flatten(params));

In [24]:
@time opt = optimize(od, params_flat, MomentumGradientDescent(), option1)
@time opt = optimize(od, opt.minimizer, BFGS(), option2)

Iter     Function value   Gradient norm 
     0     2.985873e+00     7.834282e+01
    50     1.526459e-01     4.975577e-01
  1.712626 seconds (1.32 M allocations: 381.990 MiB, 5.33% gc time)
Iter     Function value   Gradient norm 
     0     1.526459e-01     4.975577e-01
    50     1.293551e-05     5.973548e-03
   100     1.228111e-06     1.489516e-03
  1.674767 seconds (1.20 M allocations: 517.802 MiB, 6.71% gc time)


Results of Optimization Algorithm
 * Algorithm: BFGS
 * Starting Point: [0.7714624089484299,0.4081438987851545, ...]
 * Minimizer: [0.23058665114086965,0.36503006495754525, ...]
 * Minimum: 1.228111e-06
 * Iterations: 100
 * Convergence: false
   * |x - x'| < 1.0e-32: false 
     |x - x'| = 7.41e-03 
   * |f(x) - f(x')| / |f(x)| < 1.0e-32: false
     |f(x) - f(x')| / |f(x)| = NaN 
   * |g(x)| < 1.0e-08: false 
     |g(x)| = 1.49e-03 
   * stopped by an increasing objective: false
   * Reached Maximum Number of Iterations: true
 * Objective Calls: 440
 * Gradient Calls: 440

In [25]:
loss_wrap(opt.minimizer)

1.2281113328416858e-6

In [26]:
dydt_pred = predict_dt(opt.minimizer, t)
plot(t[:], f1.(t[:] ,y_true), label="dy/dt true")
plot!(t[:], dydt_pred[:],lw=0,label="dy/dt predict",
    marker=:circle,markerstrokewidth = 0,markersize=3)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0 
 
 
 2.5 
 
 
 5.0 
 
 
 -1.0 
 
 
 -0.5 
 
 
 0.0 
 
<polyline clip-path="url(#clip02)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 45.9692,171.172 49.7612,149.232 53.5532,129.49 57.3452,111.845 61.1372,96.2051 64.9292,82.4813 68.7212,70.5903 72.5132,60.4509 76.3052,51.9839 80.0972,45.1104 
 83.8892,39.7507 87.6812,35.8246 91.4732,33.2504 95.2652,31.944 99.0572,31.8191 102.849,32.7872 106.641,34.7577 110.433,37.6373 114.225,41.3307 118.017,45.7406 
 121.809,50.7687 125.601,56.3155 129.393,62.2808 133.185,68.5649 136.977,75.0686 140.769,81.6943 144.561,88.3458 148.353,94.9288 152.145,101.353 155.937,107.531 
 159.729,113.382 163.521,118.831 167.313,123.807 171.105,128.246 174.897,132.089 178.689,135.284 182.481,137.787 186.273,139.565 190.065,140.592 193.857,140.851 
 197.649,140.33 201.441,139.029 205.233,136.954 209.025,134.118 212.817,130.546 216.609,126.269 220.401,121.327 224.193,115.766 227.985,109.637 231.777,102.999 
 235.569,95.9158 239.361,88.4543 243.153,80.6872 246.945,72.6902 250.737,64.5405 254.529,56.3189 258.321,48.107 262.113,39.9859 265.905,32.0356 269.697,24.3337 
 273.489,16.9546 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#e26f46; stroke-width:0; stroke-opacity:1; fill:none" points="
 45.9692,171.017 49.7612,149.424 53.5532,129.613 57.3452,111.813 61.1372,96.076 64.9292,82.3439 68.7212,70.5057 72.5132,60.4385 76.3052,52.0292 80.0972,45.1819 
 83.8892,39.8162 87.6812,35.8609 91.4732,33.2476 95.2652,31.9054 99.0572,31.7574 102.849,32.7193 106.641,34.6999 110.433,37.602 114.225,41.3243 118.017,45.7632 
 121.809,50.8144 125.601,56.3744 129.393,62.3412 133.185,68.6153 136.977,75.0993 140.769,81.6988 144.561,88.322 148.353,94.8798 152.145,101.286 155.937,107.456 
 159.729,113.312 163.521,118.775 167.313,123.773 171.105,128.241 174.897,132.116 178.689,135.343 182.481,137.876 186.273,139.676 190.065,140.712 193.857,140.966 
 197.649,140.426 201.441,139.092 205.233,136.973 209.025,134.09 212.817,130.469 216.609,126.148 220.401,121.171 224.193,115.589 227.985,109.459 231.777,102.841 
 235.569,95.8011 239.361,88.4042 243.153,80.718 246.945,72.8097 250.737,64.7454 254.529,56.5892 258.321,48.4027 262.113,40.2438 265.905,32.1667 269.697,24.2212 
 273.489,16.4526 
 "/>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 dy/dt true 
 
 
 
 
 dy/dt predict

In [27]:
plot(t[:], y_true, label="y true")
y_pred = predict(opt.minimizer, t)
plot!(t[:], y_pred[:],lw=0,label="y predict",
     marker=:circle,markerstrokewidth = 0,markersize=3)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0 
 
 
 2.5 
 
 
 5.0 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
<polyline clip-path="url(#clip02)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 45.9692,16.4526 49.7612,24.6687 53.5532,31.2425 57.3452,36.3433 61.1372,40.1326 64.9292,42.765 68.7212,44.3883 72.5132,45.1438 76.3052,45.1663 80.0972,44.5846 
 83.8892,43.5213 87.6812,42.0925 91.4732,40.408 95.2652,38.5709 99.0572,36.6782 102.849,34.8194 106.641,33.0769 110.433,31.5261 114.225,30.235 118.017,29.2641 
 121.809,28.6658 125.601,28.485 129.393,28.7588 133.185,29.516 136.977,30.7778 140.769,32.5573 144.561,34.8604 148.353,37.6859 152.145,41.0254 155.937,44.8631 
 159.729,49.176 163.521,53.9339 167.313,59.1024 171.105,64.6416 174.897,70.5074 178.689,76.6516 182.481,83.0221 186.273,89.5628 190.065,96.2135 193.857,102.914 
 197.649,109.604 201.441,116.221 205.233,122.705 209.025,128.996 212.817,135.036 216.609,140.766 220.401,146.131 224.193,151.083 227.985,155.573 231.777,159.558 
 235.569,163.003 239.361,165.873 243.153,168.144 246.945,169.792 250.737,170.805 254.529,171.172 258.321,170.89 262.113,169.963 265.905,168.401 269.697,166.22 
 273.489,163.446 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#e26f46; stroke-width:0; stroke-opacity:1; fill:none" points="
 45.9692,16.4526 49.7612,24.6745 53.5532,31.2621 57.3452,36.3663 61.1372,40.1487 64.9292,42.77 68.7212,44.3843 72.5132,45.1359 76.3052,45.1599 80.0972,44.5831 
 83.8892,43.5253 87.6812,42.1006 91.4732,40.4174 95.2652,38.5788 99.0572,36.682 102.849,34.8178 106.641,33.0703 110.433,31.5158 114.225,30.2232 118.017,29.2529 
 121.809,28.6574 125.601,28.4809 129.393,28.7593 133.185,29.521 136.977,30.7861 140.769,32.5676 144.561,34.8709 148.353,37.6943 152.145,41.0293 155.937,44.8606 
 159.729,49.1664 163.521,53.9189 167.313,59.0842 171.105,64.623 174.897,70.4911 178.689,76.6394 182.481,83.0151 186.273,89.5618 190.065,96.2205 193.857,102.93 
 197.649,109.629 201.441,116.253 205.233,122.741 209.025,129.032 212.817,135.067 216.609,140.788 220.401,146.142 224.193,151.079 227.985,155.555 231.777,159.528 
 235.569,162.962 239.361,165.826 243.153,168.096 246.945,169.75 250.737,170.774 254.529,171.158 258.321,170.898 262.113,169.994 265.905,168.448 269.697,166.271 
 273.489,163.475 
 "/>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y true 
 
 
 
 
 y predict