In [1]:
using Optim
using Plots

In [2]:
default(size = (300, 200)) # plot size

# Generate data

In [3]:
f1(x) = x^2/20 + sin(2*x)

f1 (generic function with 1 method)

In [4]:
x = reshape([-10:0.1:10;],1,:) # shape = [n_input,n_sample]
y_true = f1.(x)
print(size(x), size(y_true))
plot(x[:], y_true[:])

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -10 
 
 
 -5 
 
 
 0 
 
 
 5 
 
 
 10 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 3 
 
 
 4 
 
 
 5 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

# Build NN

In [5]:
function init_weights(;n_in=1, n_hidden=10, n_out=1)
    W1 = randn(n_hidden, n_in) # for left multiply W1*x
    b1 = zeros(n_hidden)
    W2 = randn(n_out, n_hidden)
    b2 = zeros(n_out)
    params = [W1, b1, W2, b2]
    return params
end

params = init_weights()

4-element Array{Array{Float64,N} where N,1}:
 [-0.0278082; -0.771406; … ; 1.38799; 0.401616]    
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [-1.30763 -0.275188 … 0.592371 -0.269968]         
 [0.0]                                             

In [6]:
params_flat = collect(Iterators.flatten(params))
sizes = map(size, params)

4-element Array{Tuple{Int64,Vararg{Int64,N} where N},1}:
 (10, 1)
 (10,)  
 (1, 10)
 (1,)   

In [7]:
function predict(params, x; act=tanh)

    W1, b1, W2, b2 = params
    a = act.(W1*x .+ b1)
    y = W2*a .+ b2
    return y
end

predict (generic function with 1 method)

In [8]:
function unflatten(params_flat)
    params = []
    i1 = 1
    for s in sizes # sizes is defined outside of the function
        l = reduce(*, s) # size -> length
        i2 = i1+l
        #p = reshape(params_flat[i1:i2-1], s)
        p = reshape(view(params_flat,i1:i2-1), s)
        push!(params, p)
        i1 = i2
    end 
    return params
end

unflatten (generic function with 1 method)

In [9]:
y_pred = predict(params, x)

1×201 Array{Float64,2}:
 -0.0483492  -0.0449918  -0.0416304  …  0.0416304  0.0449918  0.0483492

In [10]:
plot(x[:], y_pred[:])

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -10 
 
 
 -5 
 
 
 0 
 
 
 5 
 
 
 10 
 
 
 -0.3 
 
 
 -0.2 
 
 
 -0.1 
 
 
 0.0 
 
 
 0.1 
 
 
 0.2 
 
 
 0.3 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

In [11]:
function loss_func(params, x, y_true)
    y_pred = predict(params, x)
    loss = mean(abs2, y_pred - y_true)
    return loss
end

loss_func (generic function with 1 method)

In [12]:
loss_func(params, x, y_true)

5.656412210721413

# Optim.jl

Objective function should only take one variable.

In [13]:
# use global x and y for now
function loss_wrap(params_flat)
    params = unflatten(params_flat)
    return loss_func(params, x, y_true)
end

loss_wrap (generic function with 1 method)

In [14]:
loss_wrap(params_flat)

5.656412210721413

## Built-in Forward autodiff

- http://julianlsolvers.github.io/Optim.jl/stable/algo/autodiff/

Seems to speed up the optimizer by 200%

In [15]:
od = OnceDifferentiable(loss_wrap, params_flat; autodiff =:forward);
typeof(od)

NLSolversBase.OnceDifferentiable{Float64,Array{Float64,1},Array{Float64,1},Val{false}}

Do several steps of Momentum Gradient Descent to approach minimum, and then use BFGS to converge to minimum.

In [16]:
option1 = Optim.Options(iterations = 50, show_trace=true, show_every=10)
option2 = Optim.Options(iterations = 1000, show_trace=true, show_every=100)

Optim.Options{Float64,Void}(1.0e-32, 1.0e-32, 1.0e-8, 0, 0, 0, false, 1000, false, true, false, 100, nothing, NaN)

In [17]:
params = init_weights(n_hidden = 10) # re-initialize weight
params_flat = collect(Iterators.flatten(params));

In [18]:
@time opt = optimize(od, params_flat, MomentumGradientDescent(), option1)
@time opt = optimize(od, opt.minimizer, BFGS(), option2)

Iter     Function value   Gradient norm 
     0     5.799849e+00     7.657934e+00
    10     3.415284e+00     3.092906e+00
    20     2.970093e+00     1.651941e+00
    30     2.818393e+00     9.007129e-01
    40     2.753465e+00     5.701517e-01
    50     2.714373e+00     4.790328e-01
  1.655316 seconds (1.02 M allocations: 281.380 MiB, 4.24% gc time)
Iter     Function value   Gradient norm 
     0     2.714373e+00     4.790328e-01
   100     2.986081e-01     3.321615e-01
   200     2.604607e-01     5.373157e-01
   300     2.301291e-01     1.117197e+00
   400     1.353001e-01     3.068037e-01
   500     1.341652e-01     6.392359e-02
   600     1.334905e-01     6.285966e-02
   700     1.331568e-01     1.071997e-01
   800     1.328820e-01     4.068853e-02
   900     1.328434e-01     3.323979e-02
  1000     1.309043e-01     2.669517e-01
  4.842897 seconds (1.99 M allocations: 3.214 GiB, 10.64% gc time)


Results of Optimization Algorithm
 * Algorithm: BFGS
 * Starting Point: [0.8884750650717351,-0.6476721342028069, ...]
 * Minimizer: [0.9559189983520852,-0.7618939200771578, ...]
 * Minimum: 1.309043e-01
 * Iterations: 1000
 * Convergence: false
   * |x - x'| < 1.0e-32: false 
     |x - x'| = 4.14e-01 
   * |f(x) - f(x')| / |f(x)| < 1.0e-32: false
     |f(x) - f(x')| / |f(x)| = 2.78e-04 
   * |g(x)| < 1.0e-08: false 
     |g(x)| = 2.67e-01 
   * stopped by an increasing objective: false
   * Reached Maximum Number of Iterations: true
 * Objective Calls: 2711
 * Gradient Calls: 2711

In [19]:
loss_wrap(opt.minimizer)

0.13090426472784633

In [20]:
y_pred = predict(unflatten(opt.minimizer), x)
plot(x[:], y_true[:],lw=2)
plot!(x[:], y_pred[:],lw=0,
    marker=:circle,markerstrokewidth = 0,markersize=3)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -10 
 
 
 -5 
 
 
 0 
 
 
 5 
 
 
 10 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 6 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1 
 
 
 
 
 y2